spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mariadb://localhost:3307/onetap?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:password}
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  thymeleaf:
    cache: false
    suffix: .html
  mail:
    host: HostName
    port: 587
    username: UserName
    password: Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#springdoc:
#  pathsToMatch: /api/**
server:
  port : 9096
  
aws:
  access:
    key:
      id : Id
      secret : Key
  region : ap-south-1
  s3:
    audio:
      bucket : kash-v
